### ISSUE TITLE
Small error in the "src/main.cpp" file

### ISSUE THREAD

**Issue by brightprogrammer** [enginmanap/limonEngine#113]
there is a small error in the "src/main.cpp" file. In line 148, 140 & 152 of the main.cpp file, you are using something like "std::__cxx11::string" which raises an error while building the project. I tried replacing it with "std::string" and then it compiled!

I don't even know whether this is an issue or not, I am new to all these things. I just think that you are doing a very great job!

**Comment by enginmanap** [comment]
Hi!

It is definetely an error. My IDE adds these on refactors, and sometimes I miss them and commit like that, sorry. I don't have a pc at hand, but I would accept a PR if you already fixed it. If not I will fix it in a couple of days.

**Comment by enginmanap** [comment]
Fixed by #114 thanks @brightprogrammer !
