### ISSUE TITLE
Assets removed from source which prevents demos from launching

### ISSUE THREAD

**Issue by sunnystormy** [enginmanap/limonEngine#55]
Built the stable release, but the demo XML files won't launch because "/Data/Textures/Menu/mayanMap-loading.png" isn't included in the source for some reason. Mind including that? Thank you!

**Comment by jmcph4** [comment]
Has this seen a fix yet? I pulled from `master` last night and this was an issue I encountered also (after dealing with #70).

**Comment by enginmanap** [comment]
The file is added to repository to enable launching the engine without the releases. The actual fix will be not requiring any hardcoded file.

**Comment by enginmanap** [comment]
This issue was fixed with Debian support work, closing as done.
