### ISSUE TITLE
Create way to navigate editor mode with laptop trackpad.

### ISSUE THREAD

**Issue by sunnystormy** [enginmanap/limonEngine#56]
I'm trying to edit the default scene with a laptop trackpad, so I do not have a third button to pivot around. Could you please add a way to navigate scenes without an external mouse?

Thank you!

**Comment by enginmanap** [comment]
Hi,

In editor mode, screen sides are used for looking around. You shouldn't need a middle button. Move the mouse at the edge you want to look at. 

The gotcha there is, Editor windows (Object, world, animation) has precedence over all other controls. If an editor window is directly at the edge, look around will be blocked. I just added a image hoping it would explain better.

![lookaround](https://user-images.githubusercontent.com/237148/45628637-28af2980-ba9d-11e8-84da-bd370cc5f995.png)

**Comment by sunnystormy** [comment]
@enginmanap Thank you for this! I'm enjoying the ability to navigate scenes on my laptop now. Cheers!

**Comment by enginmanap** [comment]
I updated the documentation to cover this information, closing the issue.
