### ISSUE TITLE
Status of Features?

### ISSUE THREAD

**Issue by sunnystormy** [enginmanap/limonEngine#57]
Does the engine also have:

-Programmable shaders?
-Particle emitters/effects?
-The ability to parent a 3D model to the camera (in an FPS game, showing the weapon/item the character is holding)?

I think if you added these three things (if they don't already exist) you'd be able to cover the "just enough" requirements of most games. Thank you!

**Comment by sunnystormy** [comment]
@enginmanap Regarding the shader issue, I was wondering if you could create a GUI window (with an editable text box) that basically allows the user to write the shader code inside of the editor? This would be a property you could select for any 3D scene entity, and then you could export the shader code (vertex/fragment) just like you would the XML map files.

**Comment by enginmanap** [comment]
I added the mentioned features to roadmap. Closing the issue, I will open ones for the features as they became feasible.
