### ISSUE TITLE
Uninitialised variable `animationTimeNew` in `ModelAsset::getTransformBlended` code

### ISSUE THREAD

**Issue by jmcph4** [enginmanap/limonEngine#75]
During standard build process:

    [ 59%] Building CXX object CMakeFiles/LimonEngine.dir/src/Assets/ModelAsset.cpp.o
    src/Assets/ModelAsset.cpp: In member function ‘bool ModelAsset::getTransformBlended(std::__cxx11::string, long int, bool, std::__cxx11::string, long int, bool, float, std::vector<glm::tmat4x4<float, (glm::precision)0u> >&) const’:
    src/Assets/ModelAsset.cpp:456:115: warning: ‘animationTimeNew’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             traverseAndSetTransform(rootNode, parentTransform, currentAnimationNew, animationTimeNew, transformMatrix);
                                                                                                                       ^

The variable in question `animationTimeNew`, is declared here:

https://github.com/enginmanap/limonEngine/blob/3e8bde062c37dc75da4a9a701895c8d94d594a84/src/Assets/ModelAsset.cpp#L420

**Comment by jmcph4** [comment]
See #76 for review

**Comment by jmcph4** [comment]
Just thought I'd provide an update on this. As of (at least) 022e002, this is the build output:

    [ 59%] Building CXX object CMakeFiles/LimonEngine.dir/src/Assets/ModelAsset.cpp.o
    src/Assets/ModelAsset.cpp: In member function ‘bool ModelAsset::getTransformBlended(std::__cxx11::string, long int, bool, std::__cxx11::string, long int, bool, float, std::vector<glm::tmat4x4<float, (glm::precision)0u> >&) const’:
    src/Assets/ModelAsset.cpp:467:108: warning: ‘animationTimeNew’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                                            currentAnimationNew, animationTimeNew, blendFactor, transformMatrix);
                                                                                                                ^
    src/Assets/ModelAsset.cpp:467:108: warning: ‘animationTimeOld’ may be used uninitialized in this function [-Wmaybe-uninitialized]

Any word on a fix for this?

**Comment by enginmanap** [comment]
Sorry it is taking long, but I am trying to finish up some other development. I didn't have time to look into this yet.

**Comment by enginmanap** [comment]
Hey, I merged your commit yesterday, and made another to fix the second one. Thanks.

Closing as done.
