### ISSUE TITLE
Unused variable `childCount` in `WorldLoader::loadObject` code

### ISSUE THREAD

**Issue by jmcph4** [enginmanap/limonEngine#77]
During standard build process:

    [ 64%] Building CXX object CMakeFiles/LimonEngine.dir/src/WorldLoader.cpp.o
    src/WorldLoader.cpp: In static member function ‘static std::vector<std::unique_ptr<WorldLoader::ObjectInformation> > WorldLoader::loadObject(AssetManager*, tinyxml2::XMLElement*, std::unordered_map<std::__cxx11::basic_string<char>, std::shared_ptr<Sound> >&, LimonAPI*, PhysicalRenderable*)’:
    src/WorldLoader.cpp:495:22: warning: unused variable ‘childCount’ [-Wunused-variable]
                 uint32_t childCount = std::stoi(childrenCountNode->GetText());
                          ^~~~~~~~~~

The variable in question `childCount`, is declared here:

https://github.com/enginmanap/limonEngine/blob/3e8bde062c37dc75da4a9a701895c8d94d594a84/src/WorldLoader.cpp#L495

**Comment by jmcph4** [comment]
See #78

**Comment by enginmanap** [comment]
I was trying to add a safety check there, but then realized xml parsing is not working like that :-). Merged your PR, closing the issue as fixed.
