### ISSUE TITLE
Incorrect asset extension file path in `AssetManager.h`

### ISSUE THREAD

**Issue by jmcph4** [enginmanap/limonEngine#79]
When running the engine, the startup process complains of a missing asset extension file. After hooking up GDB to the engine and single-stepping through the construction of `GameEngine`, a variable `ASSET_EXTENSIONS_FILE` is defined here like so:

https://github.com/enginmanap/limonEngine/blob/173cca96a43daa2c7e2f608889e7a579b2d5e3d1/src/Assets/AssetManager.h#L87

The actual directory is capitalised, i.e. `Engine`.

**Comment by enginmanap** [comment]
merged.
