### ISSUE TITLE
Missing file or (likely) incorrect file path in default world files

### ISSUE THREAD

**Issue by jmcph4** [enginmanap/limonEngine#81]
When running the engine:

    $ ./build/LimonEngine
    No world file specified, trying to load ./Data/Maps/World001.xml
    "fullScreen" setting not found, defaulting to falseOptions loaded successfully
    SDL started.
    trying to load shared library ./libcustomTriggers.so
    Custom Trigger load failed!
    Custom Actor load failed!
    Custom Player extension load failed!
    GLEW Init: Success!
    Maximum number of texture image units is 16
    Rendererer: Mesa DRI Intel(R) Bay Trail 
    GL version: 3.3 (Core Profile) Mesa 13.0.6
    Supported GLSL version is 3.30
    found 169 extensions.
    Cubemap array support is present. 
    Uniform alignment size is 16
    Uniform maxVertexUniformBlockCount size is 14
    read name as ./Data/Maps/World001.xml
    ERROR::ASSIMP::Unable to open file "./Data/Models/EasyFPS/EasyFPS.fbx".
    AL lib: (EE) alc_cleanup: 1 device not closed

Offending file path can be found here:

https://github.com/enginmanap/limonEngine/blob/5095ada110bd3d98003c4a401cdabe88f5851303/Data/Maps/World001.xml#L18

As of 74902fd, there is no file matching this exact path; however, there is a very close match at `Data/Models/EasyFPS/easyFPS.fbx`. 

Note that when this file is renamed to match the specified file path, a parser error is thrown:

    $ ./build/LimonEngine
    No world file specified, trying to load ./Data/Maps/World001.xml
    "fullScreen" setting not found, defaulting to falseOptions loaded successfully
    SDL started.
    trying to load shared library ./libcustomTriggers.so
    Custom Trigger load failed!
    Custom Actor load failed!
    Custom Player extension load failed!
    GLEW Init: Success!
    Maximum number of texture image units is 16
    Rendererer: Mesa DRI Intel(R) Bay Trail 
    GL version: 3.3 (Core Profile) Mesa 13.0.6
    Supported GLSL version is 3.30
    found 169 extensions.
    Cubemap array support is present. 
    Uniform alignment size is 16
    Uniform maxVertexUniformBlockCount size is 14
    read name as ./Data/Maps/World001.xml
    ERROR::ASSIMP::FBX-Parser (TOK_DATA, line 1, col 8) unexpected token, expected TOK_KEY
    AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by enginmanap** [comment]
This is a casing error, file name should be updated to "EasyFPS.fbx". The FBX parsing error is new to me, can you share your Assimp version?

**Comment by jmcph4** [comment]
@enginmanap The parsing error might be a false positive on my part, that file is under Git LFS, which would explain the parser error:

    $ cat Data/Models/EasyFPS/EasyFPS.fbx
    version https://git-lfs.github.com/spec/v1
    oid sha256:99f4766a3651bae2c8dd8d2610eab0ecd8230a29dbdb8e75315bd36286383553
    size 1520268

**Comment by enginmanap** [comment]
It might be. That commit is the first one I made with Git LFS :-)

**Comment by enginmanap** [comment]
Closing as fix merged.
