### ISSUE TITLE
Missing asset: `World001.aiwalk`

### ISSUE THREAD

**Issue by jmcph4** [enginmanap/limonEngine#85]
As of current `master` (i.e. d6fc943), the engine fails to start up and complains with:

    Error loading XML ./Data/Maps/World001.aiwalk: XML_ERROR_FILE_NOT_FOUND

The apparently offending file `Data/Maps/World001.aiwalk` is absent from source control (at least on current `master` branch).

**Comment by enginmanap** [comment]
Hi!

That is a saved copy of AIWalkGrid generated for the map. If the map is big, generating it can take minutes, so I added saving it. You should generate that file before releasing your map, but if the file is not found Limon will auto generate the data. When the map is loaded, you can switch to editor mode using F2 and use the button "Save AI walk Grid" on world properties window, at the bottom. That will save the file.

If you change the map after doing this, your AI may walk through walls etc. You need to click that button again, it automatically overrides if file exists.

**Comment by enginmanap** [comment]
Sorry I didn't get you said engine didn't launch. It should, can you share the full log please? Maybe I didn't handle something as I should have.

**Comment by enginmanap** [comment]
By the way, I just checked out the commit you mentioned, and successfully launched the engine. You should see these lines:

```
Error loading XML ./Data/Maps/Testd001.aiwalk: XML_ERROR_FILE_NOT_FOUND
Possible results: AI actors not moving and very slow map load
Root node  (10.000000, 3.000000, 20.000000) is movable, AI walk grid generation starts.
Walk grid creation finished with 6880 nodes between vec3(-45.000000, -0.001327, -40.000000), vec3(44.000000, 11.264699, 39.000000)
Finished generating AI walk grid, created 520 nodes, checked for collision 7132 times.
```

 Just to be complete, sharing the full log:

```
D:\engin\Documents\sourceTree\LimonEngine\cmake-build-debug\LimonEngine.exe
No world file specified, trying to load ./Data/Maps/World001.xml
Options loaded successfully
SDL started.
trying to load shared library libcustomTriggers.dll
Trigger register method found
registered Trigger: CoinPickUpOnTrigger
registered Trigger: MayanCoinPickup
registered Trigger: MayanLever
registered Trigger: UpdateGuiTextOnTrigger
Actor register method found
registered Actor: Cowboy Enemy
registered Actor: ENEMY_AI_SWAT
Player extension register method found 
registered Player extension: CowboyShooterExtension
registered Player extension: ShooterPlayerExtension
GLEW Init: Success!
Maximum number of texture image units is 32
Rendererer: GeForce GTX 1070/PCIe/SSE2
GL version: 3.3.0 NVIDIA 417.35
Supported GLSL version is 3.30 NVIDIA via Cg compiler
found 379 extensions.
Cubemap array support is present. 
Uniform alignment size is 256
Uniform maxVertexUniformBlockCount size is 14
read name as ./Data/Maps/Testd001.xml
add animation with name MainCharacterSkillet|MainAnimation
add animation with name MainCharacterSkillet|MainCharacterSkillet|MainCharacterSkillet|Sword|Take 001|BaseLa
animation created and added to sections
animation created and added to sections
animation created and added to sections
animation created and added to sections
animation created and added to sections
animation created and added to sections
animation created and added to sections
animation created and added to sections
libpng warning: iCCP: known incorrect sRGB profile
Uniform "specularSampler" could not be set
bind pose returned. for animation name []
Font manager started
atlas h: 17, w 16
No music found.
World doesn't have Object Groups clause.
Uniform "specularSampler" could not be set
add animation with name AnimationSet0
add animation with name AnimationSet1
add animation with name AnimationSet2
bind pose returned. for animation name []
set normal texture ./Data/Textures/PirateCoin/normal.jpg
Texture request has 2 elements. Attempting to extract embedded texture. 
Texture request has 2 elements. Attempting to extract embedded texture. 
set (embedded) setSpecularTexture texture *1|./Data/Models/Swat/Swat.fbx
Texture request has 2 elements. Attempting to extract embedded texture. 
set (embedded) setNormalTexture texture *2|./Data/Models/Swat/Swat.fbx
Texture request has 2 elements. Attempting to extract embedded texture. 
Texture request has 2 elements. Attempting to extract embedded texture. 
set (embedded) setSpecularTexture texture *4|./Data/Models/Swat/Swat.fbx
Texture request has 2 elements. Attempting to extract embedded texture. 
set (embedded) setNormalTexture texture *5|./Data/Models/Swat/Swat.fbx
add animation with name mixamo.com
searching mixamo animations at path: ./Data/Models/Swat/Mixamo
add animation with name death from the front|death from the front|mixamo.com
add animation with name Firing Rifle|Firing Rifle|mixamo.com
add animation with name Hit Reaction|Hit Reaction|mixamo.com
add animation with name idle|idle|mixamo.com
add animation with name run forward|run forward|mixamo.com
add animation with name Shoot Rifle|Shoot Rifle|mixamo.com
add animation with name walk forward|walk forward|mixamo.com
bind pose returned. for animation name []
Start generating AI walk grid
warning btCollisionDispatcher::needsCollision: static-static collision!
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Error loading XML ./Data/Maps/Testd001.aiwalk: XML_ERROR_FILE_NOT_FOUND
Possible results: AI actors not moving and very slow map load
Root node  (10.000000, 3.000000, 20.000000) is movable, AI walk grid generation starts.
Walk grid creation finished with 6880 nodes between vec3(-45.000000, -0.001327, -40.000000), vec3(44.000000, 11.264699, 39.000000)
Finished generating AI walk grid, created 520 nodes, checked for collision 7132 times.
Loading animation ./Data/Animations/rotateCoin.xml
Animation rotateCoin loaded
Light does not have ID. This is depricated, and will be removed!
Light does not have ID. This is depricated, and will be removed!
First enter trigger code deserialization failed.
enter trigger code deserialization failed.
Exit trigger code deserialization failed.
enter trigger code deserialization failed.
Exit trigger code deserialization failed.
atlas h: 21, w 27
atlas h: 63, w 61
atlas h: 17, w 16
atlas h: 63, w 61
World load found 24 objects and 18 unused IDs.
```

**Comment by jmcph4** [comment]
@enginmanap There's been a fair amount of progress since this was opened, so I'll just post what I have currently:

    $ ./build/LimonEngine
    No world file specified, trying to load ./Data/Maps/World001.xml
    Options loaded successfully
    SDL started.
    trying to load shared library ./libcustomTriggers.so
    Custom Trigger load failed!
    Custom Actor load failed!
    Custom Player extension load failed!
    GLEW Init: Success!
    Maximum number of texture image units is 16
    Rendererer: Mesa DRI Intel(R) Bay Trail 
    GL version: 3.3 (Core Profile) Mesa 13.0.6
    Supported GLSL version is 3.30
    found 169 extensions.
    Cubemap array support is present. 
    Uniform alignment size is 16
    Uniform maxVertexUniformBlockCount size is 14
    read name as ./Data/Maps/World001.xml
    libpng warning: iCCP: known incorrect sRGB profile
    add animation with name MainCharacterSkillet|MainAnimation
    add animation with name MainCharacterSkillet|MainCharacterSkillet|MainCharacterSkillet|Sword|Take 001|BaseLa
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    fragment type shader ./Engine/Shaders/Model/fragment.glsl could not be compiled:
    0:108(2): error: `return' with wrong type int, in function `ShadowCalculationPoint' returning float
    
    Linking failed: 
    error: linking with uncompiled shader
    Uniform "diffuseSampler" could not be set
    Uniform "ambientSampler" could not be set
    Uniform "specularSampler" could not be set
    Uniform "opacitySampler" could not be set
    Uniform "opacitySampler" could not be set
    Uniform "shadowSamplerDirectional" could not be set
    Uniform "shadowSamplerPoint" could not be set
    bind pose returned. for animation name []
    Font manager started
    atlas h: 17, w 16
    No music found.
    World doesn't have any object Groups.
    fragment type shader ./Engine/Shaders/Model/fragment.glsl could not be compiled:
    0:108(2): error: `return' with wrong type int, in function `ShadowCalculationPoint' returning float
    
    Linking failed: 
    error: linking with uncompiled shader
    Uniform "diffuseSampler" could not be set
    Uniform "ambientSampler" could not be set
    Uniform "specularSampler" could not be set
    Uniform "opacitySampler" could not be set
    Uniform "opacitySampler" could not be set
    Uniform "shadowSamplerDirectional" could not be set
    Uniform "shadowSamplerPoint" could not be set
    add animation with name AnimationSet0
    add animation with name AnimationSet1
    add animation with name AnimationSet2
    bind pose returned. for animation name []
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    set (embedded) setSpecularTexture texture *1|./Data/Models/Swat/Swat.fbx
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    set (embedded) setNormalTexture texture *2|./Data/Models/Swat/Swat.fbx
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    set (embedded) setSpecularTexture texture *4|./Data/Models/Swat/Swat.fbx
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    set (embedded) setNormalTexture texture *5|./Data/Models/Swat/Swat.fbx
    add animation with name mixamo.com
    searching mixamo animations at path: ./Data/Models/Swat/Mixamo
    add animation with name walk forward|walk forward|mixamo.com
    add animation with name run forward|run forward|mixamo.com
    add animation with name death from the front|death from the front|mixamo.com
    add animation with name Shoot Rifle|Shoot Rifle|mixamo.com
    add animation with name Hit Reaction|Hit Reaction|mixamo.com
    add animation with name idle|idle|mixamo.com
    add animation with name Firing Rifle|Firing Rifle|mixamo.com
    bind pose returned. for animation name []
    Actor with given name ENEMY_AI_SWAT can't be created. Please check if extensions loaded successfully.
    Error loading XML ./Data/Maps/World001.aiwalk: XML_ERROR_FILE_NOT_FOUND
    Possible results: AI actors not moving and very slow map load
    Start generating AI walk grid
    Root node  (10.000000, 3.000000, 20.000000) is movable, AI walk grid generation starts.
    Walk grid creation finished with 6880 nodes between vec3(-45.000000, 0.000000, -40.000000), vec3(44.000000, 11.264699, 39.000000)
    Finished generating AI walk grid, created 520 nodes, checked for collision 7132 times.
    Loading animation ./Data/Animations/rotateCoin.xml
    Animation rotateCoin loaded
    First enter trigger code deserialization failed.
    First enter trigger code deserialization failed.
    enter trigger code deserialization failed.
    Exit trigger code deserialization failed.
    First enter trigger code deserialization failed.
    enter trigger code deserialization failed.
    Exit trigger code deserialization failed.
    atlas h: 21, w 27
    atlas h: 63, w 61
    atlas h: 17, w 16
    atlas h: 63, w 61
    world ID repetition on trigger detected! gui element with id 1
    world ID verification failed
    Waiting for AI route threads to finish. 
    AI route threads to finished.
    WorldLoader didn't hand out a valid world. exiting..
    AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by jmcph4** [comment]
@enginmanap Working as of 022e002 with:

    $ ./build/LimonEngine
    No world file specified, trying to load ./Data/Maps/World001.xml
    Options loaded successfully
    SDL started.
    trying to load shared library ./libcustomTriggers.so
    Custom Trigger load failed!
    Custom Actor load failed!
    Custom Player extension load failed!
    GLEW Init: Success!
    Maximum number of texture image units is 16
    Rendererer: Mesa DRI Intel(R) Bay Trail 
    GL version: 3.3 (Core Profile) Mesa 13.0.6
    Supported GLSL version is 3.30
    found 169 extensions.
    Cubemap array support is present. 
    Uniform alignment size is 16
    Uniform maxVertexUniformBlockCount size is 14
    read name as ./Data/Maps/World001.xml
    libpng warning: iCCP: known incorrect sRGB profile
    add animation with name MainCharacterSkillet|MainAnimation
    add animation with name MainCharacterSkillet|MainCharacterSkillet|MainCharacterSkillet|Sword|Take 001|BaseLa
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    animation created and added to sections
    fragment type shader ./Engine/Shaders/Model/fragment.glsl could not be compiled:
    0:108(2): error: `return' with wrong type int, in function `ShadowCalculationPoint' returning float
    
    Linking failed: 
    error: linking with uncompiled shader
    Uniform "diffuseSampler" could not be set
    Uniform "ambientSampler" could not be set
    Uniform "specularSampler" could not be set
    Uniform "opacitySampler" could not be set
    Uniform "opacitySampler" could not be set
    Uniform "shadowSamplerDirectional" could not be set
    Uniform "shadowSamplerPoint" could not be set
    bind pose returned. for animation name []
    Font manager started
    atlas h: 17, w 16
    No music found.
    World doesn't have any object Groups.
    fragment type shader ./Engine/Shaders/Model/fragment.glsl could not be compiled:
    0:108(2): error: `return' with wrong type int, in function `ShadowCalculationPoint' returning float
    
    Linking failed: 
    error: linking with uncompiled shader
    Uniform "diffuseSampler" could not be set
    Uniform "ambientSampler" could not be set
    Uniform "specularSampler" could not be set
    Uniform "opacitySampler" could not be set
    Uniform "opacitySampler" could not be set
    Uniform "shadowSamplerDirectional" could not be set
    Uniform "shadowSamplerPoint" could not be set
    add animation with name AnimationSet0
    add animation with name AnimationSet1
    add animation with name AnimationSet2
    bind pose returned. for animation name []
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    set (embedded) setSpecularTexture texture *1|./Data/Models/Swat/Swat.fbx
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    set (embedded) setNormalTexture texture *2|./Data/Models/Swat/Swat.fbx
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    set (embedded) setSpecularTexture texture *4|./Data/Models/Swat/Swat.fbx
    Texture request has 2 elements. Attempting to extract embedded texture. 
    libpng warning: iCCP: known incorrect sRGB profile
    set (embedded) setNormalTexture texture *5|./Data/Models/Swat/Swat.fbx
    add animation with name mixamo.com
    searching mixamo animations at path: ./Data/Models/Swat/Mixamo
    add animation with name walk forward|walk forward|mixamo.com
    add animation with name run forward|run forward|mixamo.com
    add animation with name death from the front|death from the front|mixamo.com
    add animation with name Shoot Rifle|Shoot Rifle|mixamo.com
    add animation with name Hit Reaction|Hit Reaction|mixamo.com
    add animation with name idle|idle|mixamo.com
    add animation with name Firing Rifle|Firing Rifle|mixamo.com
    bind pose returned. for animation name []
    Actor with given name ENEMY_AI_SWAT can't be created. Please check if extensions loaded successfully.
    Error loading XML ./Data/Maps/World001.aiwalk: XML_ERROR_FILE_NOT_FOUND
    Possible results: AI actors not moving and very slow map load
    Start generating AI walk grid
    Root node  (10.000000, 3.000000, 20.000000) is movable, AI walk grid generation starts.
    Walk grid creation finished with 6880 nodes between vec3(-45.000000, 0.000000, -40.000000), vec3(44.000000, 11.264699, 39.000000)
    Finished generating AI walk grid, created 520 nodes, checked for collision 7132 times.
    Loading animation ./Data/Animations/rotateCoin.xml
    Animation rotateCoin loaded
    First enter trigger code deserialization failed.
    First enter trigger code deserialization failed.
    enter trigger code deserialization failed.
    Exit trigger code deserialization failed.
    First enter trigger code deserialization failed.
    enter trigger code deserialization failed.
    Exit trigger code deserialization failed.
    atlas h: 21, w 27
    atlas h: 63, w 61
    atlas h: 17, w 16
    atlas h: 63, w 61
    World load found 23 objects and 19 unused IDs.
    Waiting for AI route threads to finish. 
    AI route threads to finished.

**Comment by enginmanap** [comment]
I am closing the tickes as fixed. 

As side note, it looks like you didn't compile customTriggers target, so AI, shooting around and picking coins won't work (They don't exist).
