### ISSUE TITLE
__attribute__((unused)) tags break VS builds

### ISSUE THREAD

**Issue by enginmanap** [enginmanap/limonEngine#87]
It should be replaced by a macro

**Comment by XenialDan** [comment]
Same for __attribute((unused))

**Comment by onurblt** [comment]
So it should be disabled by a macro if it is a Windows build?

**Comment by enginmanap** [comment]
Actually, __attribute__ was a gcc extension, but now it is part of the C++ standart. C++14 doesn't have unused defined, but the standart allows implementations define their own. So all instances of the old version should be replaced with this:
[[gnu::unused]]

**Comment by enginmanap** [comment]
No, the standart says unknown extensions should be ignored.

**Comment by onurblt** [comment]
Ok then, I will replace them
